#!/usr/local/bin/bash
e="\x1b[";
c=$e"39;49;00m";
y=$e"93;01m";
cy=$e"96;01m";
r=$e"1;91m";
g=$e"92;01m";
m=$e"95;01m";
##########################################################
#                                                        #
#           Carliv Image Kitchen for Android             #
#     boot+recovery images copyright-2016 carliv@xda     #
#    including support for MTK powered phones images     #
#                                  modified by andrwgldmn#
##########################################################
bin="$PWD/.bin";
working="$PWD/.working";
scripts="$PWD/.scripts";
find "$bin" "$scripts" -type f ! -name "*.*" -exec chmod +x {} \;
cd "$PWD";
###########################################################

pause()
{
read -s -n 1 -p "Нажмите любую клавишу чтобы продолжить...";
}

wrong()
{
echo -e "$env - $y Неверная опция! Пожалуйста, попробуйте снова $c";
pause;
main;
}

wrongbs()
{
echo -e "$benv - $y Неверная опция! Пожалуйста, попробуйте снова $c";
pause;
boot;
}

wrongimg()
{
echo -e "$imgenv - $y Неверная опция! Пожалуйста, попробуйте снова $c";
pause;
imgmenu;
}

wrongrs()
{
echo -e "$renv - - $y Неверная опция! Пожалуйста, попробуйте снова $c";
pause;
recovery;
}

quit() 
{
cd "$working";
find . -maxdepth 1 -type f -exec rm -f {} \;
cd ../;	
clear; 
exit;
}

img_unpack()
{
if [[ "$filetype" = "bootimage" ]];
	then
	cp -f "$working"/"$workfile" boot.img > /dev/null 2>&1;
	"$scripts"/unpack_img  boot.img "$workfile";
	rm -f boot.img > /dev/null 2>&1;
	else
	cp -f "$working"/"$workfile" recovery.img > /dev/null 2>&1;
	"$scripts"/unpack_img  recovery.img "$workfile";
	rm -f recovery.img > /dev/null 2>&1;
fi;
pause;
imgmenu;
}

img_repack()
{
if [ -d "$wfolder" ]; 
	then
	"$scripts"/repack_img "$wfolder";
	else
	echo -e "Папка для перепаковки $g $wfolder$c не существует!. Вы уверены, что Вы её не удалили?";
fi;
pause;
imgmenu;
}

clean_all()
{
find . -maxdepth 1 -type f ! -name "image_info" ! -name "repack_img" ! -name "carliv" ! -name "unpack_img" ! -name "Instructions.txt" ! -name "*.img" ! -name "." ! -name ".*" ! -exec rm -f {} \; > /dev/null 2>&1;
find . -maxdepth 1 -type d ! -name ".bin" ! -name "." ! -name ".*" ! -name "boot-resources" ! -name "recovery-resources" ! -name "output" ! -name ".working" ! -name ".scripts" -exec rm -rf {} \; > /dev/null 2>&1;
echo "$y Готово! Ваша рабочая папка чиста.$c";
sleep 2;
main;	
}

clean_output()
{
cd output;
find . -maxdepth 1 -type f -exec rm -f {} \; > /dev/null 2>&1;
find . -maxdepth 1 -type d -exec rm -rf {} \; > /dev/null 2>&1;
cd ../;
echo "$y Готово! Папка 'output' чиста.$c";
sleep 2;
main;	
}

img_info()
{
cp -f "$working"/"$workfile" "$workfile" > /dev/null 2>&1;
"$scripts"/image_info "$workfile";
rm -f "$workfile" > /dev/null 2>&1;
pause;
imgmenu;
}

boot()
{
clear;
echo -e "
****************************************************
*                                                  *
*     $cy Carliv Image Kitchen for Android$c v1.3       *
* boot+recovery images copyright(c)2016$cy carliv@xda$c *
*  including support for$y MTK powered$c phones images *
*                $g LINUX x64 version$c                *
*                                                  *
*                           $r modified by andrwgldmn$c*
****************************************************
";     
###########################################################
echo " ";
cd boot-resources;
grep_boot1="$(find . -maxdepth 1 -type f | grep -i \\.img$ | sed 's/ /ftemps/g' 2>/dev/null)";
grep_boot="$(echo $grep_boot1 | sed -e 's/\.\///g' | sort -f)";
cd ../;
if [ "$grep_boot" == "" ];
then
  printf %s "В [boot-resources] нет ничего. Переместите туда что-либо и затем нажмите [B] чтобы начать сначала или [Q] чтобы выйти в главное меню, затем нажмите ENTER!"
  read bchoice;
  if [[ "$bchoice" = "B" || "$bchoice" = "b" ]]; 
	then
	boot;
  elif [[ "$bchoice" = "Q" || "$bchoice" = "q" ]]; 
	then
	main;
  else
	echo "$bchoice неверная опция"; pause; boot;
  fi;
fi;
count=0;
echo "  00. - Обновить                                    ";
echo "  0. - Выйти в главное меню                        ";
for filename in $grep_boot 
 do
 count=$(($count+1));
 filename="$(echo $filename | sed 's/ftemps/ /g')";
 file_array[$count]="$filename";
  echo "  $count. - $filename";
done
printf %s "Введите номер файла, затем нажмите ENTER: ";
read benv;
if [ "$benv" == "00" ];
    then
      boot;
fi;
if [ "$benv" == "0" ];
    then
      main;
fi;
if [ "$benv" == "" ];
    then
      benv=none;
fi;
if [ "$(echo $benv | sed 's/[0-9]*//')" == "" ] || [ "benv"=="none" ];
	then
	  file_chosen=${file_array[$benv]};
	  if [ "$file_chosen" == "" ];
      then
        wrongbs;
      else
        workfile="$file_chosen";
      fi;
	else
	  wrongbs;
fi;
yes | cp -f boot-resources/"$workfile" "$working"/"$workfile";
filetype=bootimage;
imgmenu;
}

recovery()
{
clear;
echo -e "
****************************************************
*                                                  *
*     $cy Carliv Image Kitchen for Android$c v1.3       *
* boot+recovery images copyright(c)2016$cy carliv@xda$c *
*  including support for$y MTK powered$c phones images *
*                $g LINUX x64 version$c                *
*                                                  *
*                           $r modified by andrwgldmn$c*
**************************************************** 
";     
###########################################################
echo " ";
cd recovery-resources;
grep_rec1="$(find . -maxdepth 1 -type f | grep -i \\.img$ | sed 's/ /ftemps/g' 2>/dev/null)";
grep_rec="$(echo $grep_rec1 | sed -e 's/\.\///g' | sort -f)";
cd ../;
if [ "$grep_rec" == "" ];
then
  printf %s "В [recovery-resources] нет ничего. Переместите туда что-либо и затем нажмите [R] чтобы начать сначала или [Q] чтобы выйти в главное меню, затем нажмите ENTER!"
  read rchoice;
  if [[ "$rchoice" = "R" || "$rchoice" = "r" ]]; 
	then
	recovery;
  elif [[ "$rchoice" = "Q" || "$rchoice" = "q" ]]; 
	then
	main;
  else
	echo "$rchoice неверная опция"; pause; recovery;
  fi;
fi;
count=0;
echo "  00. - Обновить                                    ";
echo "  0. - Выйти в главное меню                        ";
for filename in $grep_rec 
 do
 count=$(($count+1));
 filename="$(echo $filename | sed 's/ftemps/ /g')";
 file_array[$count]="$filename";
  echo "  $count. - $filename";
done
printf %s "Введите номер файла, затем нажмите ENTER: ";
read renv;
if [ "$renv" == "00" ];
    then
      recovery;
fi;
if [ "$renv" == "0" ];
    then
      main;
fi;
if [ "$renv" == "" ];
    then	
      renv=none;
fi;
if [ "$(echo $renv | sed 's/[0-9]*//')" == "" ] || [ "renv"=="none" ];
	then
	  file_chosen=${file_array[$renv]};
	  if [ "$file_chosen" == "" ];
      then
        wrongrs;
      else
        workfile="$file_chosen";
      fi;
	else
	  wrongrs;
fi;
yes | cp -f recovery-resources/"$workfile" "$working"/"$workfile";
filetype=recoveryimage;
imgmenu;
}

imgmenu()
{
clear;
echo -e "
****************************************************
*                                                  *
*     $cy Carliv Image Kitchen for Android$c v1.3       *
* boot+recovery images copyright(c)2016$cy carliv@xda$c *
*  including support for$y MTK powered$c phones images *
*                $g LINUX x64 version$c                *
*                                                  *
*                           $r modified by andrwgldmn$c*
****************************************************
"; 
echo " ";
echo " ";
echo -e "Ваш файл $g $workfile$c"; 
if [[ "$workfile" == *boot* || "$workfile" == *recovery* ]];
	then
	  wfolder="${workfile%.*}";
	else	  
		if [[ "$filetype" = "bootimage" ]];
			then
			wfolder=boot-"${workfile%.*}";
		else
			wfolder=recovery-"${workfile%.*}";
		fi;
fi;
echo " ";
if [ -d "$wfolder" ]; 
	then
	echo -e "Папка для перепаковки $g $wfolder$c";
	echo "Удостоверьтесь в том, что папка существует и что Вы её не удалили, ибо будет ошибка.";
	echo " ";	
fi;
###########################################################
echo " ";
echo -e "$cy 1. Разобрать$c";
echo -e "$cy 2. Собрать$c";
echo -e "$y B. Другое ядро$c";
echo -e "$y R. Другое recovery $c";
echo -e "$m I. Показать информацию$c";
echo -e "$r Q. В главное меню$c";
echo " ";
printf %s "Сделайте Ваш выбор [1,2,B,R,I,Q] затем нажмите ENTER: ";
read imgenv;
case $imgenv in
 1) img_unpack;;
 2) img_repack;;
 b|B) boot;;
 r|R) recovery;;
 i|I) img_info;;
 q|Q) main;;
 *) wrongimg;;
esac
}

main()
{
clear;
echo -e "
****************************************************
*                                                  *
*     $cy Carliv Image Kitchen for Android$c v1.3       *
* boot+recovery images copyright(c)2016$cy carliv@xda$c *
*  including support for$y MTK powered$c phones images *
*                $g LINUX x64 version$c                *
*                                                  *
*                           $r modified by andrwgldmn$c*
**************************************************** 
";     
###########################################################
echo " ";
echo " Выберите с чем будете работать.";
echo " ";
echo -e "$cy  B.   Ядро$c";
echo -e "$y  R.   Recovery$c";
echo -e "$g  C.   Очистить папку$c";
echo -e "$m  O.   Очистить 'output'$c";
echo -e "$y  P.   Инструкция";
echo -e "$r  E.   Выход$c";
echo " ";
printf %s "Сделайте Ваш выбор [B,R,C,O,P,E] затем нажмите ENTER: ";
read env;
case $env in
 b|B) boot;;
 r|R) recovery;;
 c|C) clean_all;;
 o|O) clean_output;;
 p|P) cat "$scripts"/Instructions.txt; pause; continue;;
 e|E) quit;;
 *) wrong;;
esac
###########################################################
}

while :
do
	main;
done
